# Generated by Django 3.2.6 on 2021-08-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
